name: Dart CI

on: push
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

permissions:
  contents: read

env:
  flutter_channel: 'stable' # or: 'dev' or 'beta'
  flutter_version: '1.17.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8 # v1
      with:
        channel: ${{ env.flutter_channel }}
        flutter-version: ${{ env.flutter_version }}

    - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1
      with:
        java-version: '12.x'

    - run: flutter pub get
      working-directory: iuo_mobile_app
    # - run: flutter test

    - name: build APK
      run: flutter build apk
      working-directory: iuo_mobile_app

    - name: upload APK
      uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1
      with:
        name: apk
        path: iuo_mobile_app/build/app/outputs/apk/release/app-release.apk
