name: Dart CI

on: push
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

permissions:
  contents: read

env:
  flutter_channel: 'stable' # or: 'dev' or 'beta'
  flutter_version: '1.17.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

    - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
      with:
        channel: ${{ env.flutter_channel }}
        flutter-version: ${{ env.flutter_version }}

    - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1
      with:
        java-version: '12.x'

    - run: flutter pub get
      working-directory: iuo_mobile_app
    # - run: flutter test

    - name: build APK
      run: flutter build apk
      working-directory: iuo_mobile_app

    - name: upload APK
      uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # v1
      with:
        name: apk
        path: iuo_mobile_app/build/app/outputs/apk/release/app-release.apk
